### ISSUE TITLE
Receiving email bug

### ISSUE THREAD

**Issue by egtann** [DaleWebb/mailgun#1]
I believe there's an issue receiving email. I've set up Mailgun, and everything works fine from the example curl request you've given, but when I send an email to Mailgun, which forwards content to `/mailgun`, I get the following error:

`DEBUG: invalid character 'r' looking for beginning of value`

I believe this means that Mailgun isn't sending JSON as part of that `forward()` route. If not, can we parse the incoming message as form content or mail?

**Comment by DaleWebb** [comment]
I'll try to reproduce the error

**Comment by DaleWebb** [comment]
This should now be fixed

**Comment by egtann** [comment]
Cool! I'll start to integrate email support into the response panel!
